name: Pylint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
                          # no matrix with pipenv?
          # "3.8", "3.9",
          "3.11"
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv' # caching pipenv dependencies
      - name: Install pipenv and pipx
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install Dependencies
        run: pipenv install --dev --skip-lock

      - name: Run nb
        run: chmod +x build.sh && ./build.sh
